// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okbvrklpvkepeskznqyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rYnZya2xwdmtlcGVza3pucXlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NDY1MzQsImV4cCI6MjA2NDUyMjUzNH0.oPvtKJDu6L9h3TAj8bUWaTivqrKNjjIMLnbMTKCmCYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);